"""014_media_asset_product_id

ai-rag-acl-index 2.1：media_assets 加 product_id（商品-文档关联，供 RAG 语料索引）。

- 可空、无 FK（ADR-011 无 FK 判据：products 无删除路径，FK 价值≈0、只剩阻塞）
- 加索引（按 product 查询文档用）
- 不加 shop_id（chunk ACL 键单一事实源为商品归属，见 design D3）

Revision ID: d3f7a1c9b4e2
Revises: 25a1017514aa
Create Date: 2026-08-19 13:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f7a1c9b4e2"
down_revision: str | None = "25a1017514aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_assets",
        sa.Column("product_id", sa.String(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_media_assets_product_id"),
        "media_assets",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_media_assets_product_id"),
        table_name="media_assets",
    )
    op.drop_column("media_assets", "product_id")
    # ### end Alembic commands ###
