"""006_ordering_initiated_by

Revision ID: e1674055eb99
Revises: 0ca23eb664a9
Create Date: 2026-07-21 22:47:34.821060

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1674055eb99"
down_revision: str | None = "0ca23eb664a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "initiated_by", sa.String(length=16), server_default="buyer", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "initiated_by")
    # ### end Alembic commands ###
