"""007_ordering_cart

Revision ID: ece9a7855313
Revises: e1674055eb99
Create Date: 2026-07-27 05:02:23.330395

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ece9a7855313"
down_revision: str | None = "e1674055eb99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cart_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint(
            "user_id", "product_id", name=op.f("uq_cart_items_user_id")
        ),
    )
    op.create_index("ix_cart_items_user_id", "cart_items", ["user_id"], unique=False)
    op.create_table(
        "checkout_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("buyer_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["buyer_user_id"],
            ["users.id"],
            name=op.f("fk_checkout_batches_buyer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkout_batches")),
    )
    op.add_column(
        "orders", sa.Column("checkout_batch_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        "ix_orders_checkout_batch_id", "orders", ["checkout_batch_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_orders_checkout_batch_id_checkout_batches"),
        "orders",
        "checkout_batches",
        ["checkout_batch_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_orders_checkout_batch_id_checkout_batches"),
        "orders",
        type_="foreignkey",
    )
    op.drop_index("ix_orders_checkout_batch_id", table_name="orders")
    op.drop_column("orders", "checkout_batch_id")
    op.drop_table("checkout_batches")
    op.drop_index("ix_cart_items_user_id", table_name="cart_items")
    op.drop_table("cart_items")
    # ### end Alembic commands ###
